### ISSUE TITLE
If the ShareExists and the Path is not consistent with the desired state, the resource does not update the path

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/xSmbShare#10]
If the ShareExists and the Path is not consistent with the desired state, the resource does not update the path

**Comment by johlju** [comment]
The path cannot be updated without recreating the share, since Set-SmbShare do not support the parameter `Path`, and `New-SmbShare` does. Recreating the share could potentially remove configuration that has not been enforced by the DSC configuration. We should support recreating the share, but only if the user expressively allow that by using, for example, a resource parameter `Force`.

I'm in progress moving this resource to the ComputerManagementDsc module. I will either move this issue to that repo, or solve it, depending on the time frame.

**Comment by johlju** [comment]
The content of this issue has been moved to ComputerManagementDsc as this module will soon be deprecated, and the resource has been moved there.

Thisissue need to be resolved in the new resource SmbShare. Closing this issue at this time.
